version: "3"

services:
  mailbox_service:
    image: mailbox
    build:
      context: ./Mailbox
    volumes:
      - ./Mailbox:/usr/src/
      - /usr/src/node_modules
    ports:
      - "8080:8080"
    networks:
      - extnet
      - inet

networks:
  extnet:
  inet:
    internal: true

